
name: CI/CD

on:
  push:
    branches: master
    tags: ['**']

jobs:
  build:
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v3
    
    - name: compile
      run: |
        cmake .
        make catimg

    - uses: actions/upload-artifact@v3
      with:
        name: catimg-${{ runner.os }}
        path: bin/catimg

    - name: compress
      if: startsWith(github.ref, 'refs/tags/')
      run: tar -czvf catimg-${{ runner.os }}.tar.gz -C bin catimg
    
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: catimg-${{ runner.os }}.tar.gz
